---
functional:
  - Пользователь должен иметь возможность сыграть в игру без регистрации личного кабинета
  - Пользователь должен иметь возможность зарегистрироваться для входа в личный кабинет
  - Пользователь должен иметь возможность зарегистрироваться для входа в личный кабинет с помощью уже существующих аккаунтов (Google mail, github, discord)
  - Пользователь должен иметь возможность восстановить личный кабинет при забытии пароля
  - Пользователь должен иметь возможность просматривать информацию и рейтинги игр в личном кабинете
  - Пользователь должен иметь возможность редактировать свой профиль
  - Пользователь должен иметь возможность менять настройки личного кабинета
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - При нажатии на название сайта в главном меню пользователь возвращается на главную страницу
  - Есть возможность на сайте присоединиться к сообществу
